{
 "title": "Credera - GCP - Billing Expense Dashboard",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Total Cost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT sum(cost) cost\r\nFROM    `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\nwhere cost > 0\r\nand $__timeFilter(export_time)"
    }
   ]
  },
  {
   "title": "Top 6 Project",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT project.id as Project, sum(cost) AS cost\r\nFROM `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\nwhere  $__timeFilter(export_time)\r\nGROUP BY Project \r\nORDER BY cost DESC limit 6\r\n"
    }
   ]
  },
  {
   "title": "Top 6 Resources By Tag- Environment",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT case when key = 'environment' then value  end as environment, \r\n       sum(cost) cost\r\nFROM    `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\ncross join unnest(project.labels) as b\r\nwhere cost > 0\r\nand $__timeFilter(export_time)\r\nand key= 'environment'\r\ngroup by key,value\r\norder  by 2 desc\r\nlimit  6"
    }
   ]
  },
  {
   "title": "Top Expensive Location",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT location.location as Location,  sum(cost) AS cost\r\nFROM `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\nwhere  $__timeFilter(export_time)\r\nGROUP BY Location \r\nORDER BY cost DESC limit 1"
    }
   ]
  },
  {
   "title": "Top Expensive Application",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT case when key = 'application' then value  end as application, \r\n       sum(cost) cost\r\nFROM    `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\ncross join unnest(project.labels) as b\r\nwhere cost > 0\r\nand $__timeFilter(export_time)\r\nand key= 'application'\r\ngroup by key,value\r\norder  by 2 desc\r\nlimit  1"
    }
   ]
  },
  {
   "title": "Top Expensive Application",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT service.description as service,  sum(cost) AS cost\r\nFROM `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\nwhere  $__timeFilter(export_time)\r\nGROUP BY service \r\nORDER BY cost DESC limit 1"
    }
   ]
  },
  {
   "title": "Top 6 Resources By Tag- Application",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT case when key = 'application' then value  end as application, \r\n       sum(cost) cost\r\nFROM    `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\ncross join unnest(project.labels) as b\r\nwhere cost > 0\r\nand $__timeFilter(export_time)\r\nand key= 'application'\r\ngroup by key,value\r\norder  by 2 desc\r\nlimit  6"
    }
   ]
  },
  {
   "title": "Expense - Top 5 services",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT service.description as service,  sum(cost) AS cost\r\nFROM `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\nwhere  $__timeFilter(export_time)\r\nGROUP BY service \r\nORDER BY cost DESC limit 5"
    }
   ]
  },
  {
   "title": "Expense - Top 5 Based on Location",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT location.location as Location,  sum(cost) AS cost\r\nFROM `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\nwhere  $__timeFilter(export_time)\r\nGROUP BY Location \r\nORDER BY cost DESC limit 5"
    }
   ]
  },
  {
   "title": "Top 6 Resources By Tag- Application",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "SELECT case when key = 'application' then value  end as application, \r\n       sum(cost) cost\r\nFROM    `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\ncross join unnest(project.labels) as b\r\nwhere cost > 0\r\nand $__timeFilter(export_time)\r\nand key= 'application'\r\ngroup by key,value\r\norder  by 2 desc\r\nlimit  6"
    }
   ]
  },
  {
   "title": "Expense - Based on Location",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "location": "EU",
     "orderByCol": "2",
     "orderBySort": "1",
     "rawSql": "SELECT location.location as Location, sum(cost) AS cost\r\nFROM `dmw-audit-logging.billing_data.gcp_billing_export_v1_01ED8D_E6638F_F01858`\r\nwhere  $__timeFilter(export_time)\r\nGROUP BY Location, currency\r\nORDER BY cost DESC limit 10"
    }
   ]
  }
 ]
}